name: Java CI

on:
  pull_request:
    branches:
      - master
      - release/spring-2.1
      - release/spring-2.2
      - release/spring-2.3
  push:
    branches:
      - master
      - release/spring-2.1
      - release/spring-2.2
      - release/spring-2.3

jobs:

  test:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.8.5.1

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Start Database
        run: ./docker/start_db.sh
        env:
          DOCKER_IMAGE: ${{ matrix.docker-img }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-
      - name: Info
        run: mvn -version
      - name: Test
        run: mvn --no-transfer-progress test
      - name: Collect docker logs on failure
        if: ${{ cancelled() || failure() }}
        uses: jwalton/gh-docker-logs@v1
        with:
          dest: './logs'
      - name: Tar logs
        if: ${{ cancelled() || failure() }}
        run: tar cvzf ./logs.tgz ./logs
      - name: Upload logs to GitHub
        if: ${{ cancelled() || failure() }}
        uses: actions/upload-artifact@master
        with:
          name: logs-${{github.job}}.tgz
          path: ./logs.tgz
