name: Java CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  package:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Package
        run: mvn --no-transfer-progress -DskipTests=true package

  test:

    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        docker-img:
          - docker.io/arangodb/arangodb:3.7.2

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Start Database
        run: ./docker/start_db_single_retry_fail.sh ${{ matrix.docker-img }}
      - name: Test
        run: mvn --no-transfer-progress test
      - name: Debug containers
        if: ${{ cancelled() || failure() }}
        run: ./docker/debug_containers_single.sh
